OWASP/owasp-masvs

Document/0x01-Acknowledgements.md
Document/0x03-Using_the_MASVS.md

merging preface branch to master.

Typos and additions

---

Document/0x07-V2-Data_Storage_and_Privacy_requirements.md
Document/0x08-V3-Cryptography_Verificiation_Requirements.md
Document/0x10-V5_Network_communication_requirements.md
Document/0x11-V6_Interaction_with_the_environment.md
Document/0x12-V7-Code_quality_and_build_setting_requirements.md
Document/0x14-V8-Resiliency_Against_Reverse_Engineering Requirements.md

Hello all,
this is my first attempt to add controls to the MASVS and I am still looking a bit for the right granularity / level of implementation (E.g.: how much can it be coupled to examples/technologies). Please provide as much feedback as possible, so I can provide better PRs in the future.
Grz,
Jeroen

First attempt to add content to the MASVS

---

Document/0x09-V4-Authentication_and_Session_Management Requirements.md

Using short-lived access token to avoid sending users's credentials for every request to the remote service.

Update 0x09-V4-Authentication_and_Session_Management Requirements.md

---

Document/0x90-Appendix-A_Glossary.md

Updates for glossary

---

Document/0x06-V1-Architecture_design_and_threat_modelling_requireme.md
Document/0x07-V2-Data_Storage_and_Privacy_requirements.md
Document/0x08-V3-Cryptography_Verificiation_Requirements.md
Document/0x09-V4-Authentication_and_Session_Management Requirements.md
Document/0x10-V5_Network_communication_requirements.md
Document/0x11-V6_Interaction_with_the_environment.md
Document/0x12-V7-Code_quality_and_build_setting_requirements.md
Document/0x14-V8-Resiliency_Against_Reverse_Engineering Requirements.md

Add references to all chapters

Berndtzl 1

---

generate_document.sh

This commit fixes the issue with the tables not extending to the entire page width. 
Tables in PDF are still not working properly and i will get to them later when i can.
Sorry it took two commits to get stuff sorted but this should also get rid of any image error's anyone might have recieved while building the docx file.

fix for table width in Docx file

---

Document/0x09-V4-Authentication_and_Session_Management Requirements.md

A small addition in relation to https://github.com/OWASP/owasp-masvs/issues/41

Updated 0x09: added 4.8

---

Document/0x06-V1-Architecture_design_and_threat_modelling_requireme.md

Fix for #32. Please note that installation source is already covered in 8.4

Update of V1 regarding fake appstores.

---

Document/0x10-V5_Network_communication_requirements.md

Fix for #48. During this fix I found out that the previous 5.4 & 5.7 were kind of alike. So backtracking the changes, I tried to capture the original idea behind these 2 objectives. LAstly, I rearranged them so that 2fa would be grouped and so wourld ssl/pki related materials be grouped again.

Update of ox10-V5

---

Document/0x09-V4-Authentication_and_Session_Management Requirements.md
Document/0x11-V6_Interaction_with_the_environment.md
Document/0x15-V9-Educate_users.md

First attempt for creating customer education standard to facilitate the discussion on #36.
I have also included some other controls for which I think that they were still missing.

Customer education

---

Document/0x12-V7-Code_quality_and_build_setting_requirements.md

merged 7.8 and 7.9 as both are actually part of the toolchain related security feature set.

Update 0x12-v7 for simplification

---

Document/0x11-V6-Interaction_with_the_environment.md

Making the requirement more generic so it’s also applicable to iOS

Requirement 6.8

---

Document/0x09-V4-Authentication_and_Session_Management_Requirements.md

This is related to the following conversation:
https://github.com/OWASP/owasp-masvs/issues/113

more generic recommendation

---

Document-ru/0x02-Frontispiece.md

Fixed not displaying table on git. Minimized number of rows.

Add fix for broken authors' table web representation.

---

Document/0x12-V7-Code_quality_and_build_setting_requirements.md

Possible update of 7.1 Given #128 .

Possible update of 7.1

---

README.md

I fixed a typo, changed the slack invite url, and added a few titles to URLs (out of habit)

Fixed typos & urls

---

Document-es/0x02-Frontispiece.md
Document-es/0x06-V1-Architecture_design_and_threat_modelling_requireme.md
Document-es/0x07-V2-Data_Storage_and_Privacy_requirements.md
Document-es/0x11-V6-Interaction_with_the_environment.md
Document-es/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md

Small grammar changes and table checks.
Ready for release of version 1.1

Review of Spanish Version 1.1. Ready for release.

---

README.md

Added a twitter account integration

Added twitter account

---

Document-fr/0x08-V3-Cryptography_Verification_Requirements.md

Please discard the first one from a few minutes ago and only consider this one

0x08 - First Translations (2nd attempt)

---

Document/0x02-Frontispiece.md

Updated the list of contributors

Updated contributor list

---

Document/Foreword.md
Document/SUMMARY.md

Fixes due to issues with previous PR

Quickfixes

---

Document-es/0x12-V7-Code_quality_and_build_setting_requirements.md

Updated spanish translation on the forgotten to be updated requirement.

Updated spanish translation.

---

Document-de/0x00-Header.md
Document-de/0x02-Frontispiece.md
Document-es/0x00-Header.md
Document-es/0x02-Frontispiece.md
Document-fr/0x00-Header.md
Document-fr/0x02-Frontispiece.md
Document-ja/0x00-Header.md
Document-ja/0x02-Frontispiece.md
Document-zhtw/0x00-Header.md
Document-zhtw/0x02-Frontispiece.md
Document/0x00-Header.md
Document/0x02-Frontispiece.md
Document/0x03-Using_the_MASVS.md

There's a small markup issue on page 0x03 Using the MASVS. The line before it contains HTML which I assume is to get it correct in a PDF version?

Using the masvs

---

Document/0x03-Using_the_MASVS.md

Fixed a few spelling & grammar errors.

Fix spelling

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

Code of Conduct is almost unchanged (Just changed MSTG to MASVS). 
Contributing changed quite a bit. I also added "companies or individuals" to the end of the file. If ok, I will also add to the contribution in the MSTG
- The MASVS should not be used as a platform for advertisement of commercial tools, companies or individuals.

added code of conduct and contributing

---

CONTRIBUTING.md

fix Conctributing 

---

README.md

223 clean git repo

---

CHANGELOG.md

I guess "english" should be "English".

minor typo

---

Document-zhtw/CHANGELOG.md

Translated CHANGELOG.md to zh-tw

---

.gitignore
Generated/README.txt
tools/gendocs.sh
tools/gendocsLocal.sh
tools/generate_document.sh
tools/generate_document_de.sh
tools/generate_document_es.sh
tools/generate_document_ja.sh
tools/generate_document_ru.sh
tools/generate_document_zhtw.sh

make sure we have support for local generation, but not have them in our git anymore

---

CHANGELOG.md

Updated changelog as part of the release

---

CHANGELOG.md
Document-de/CHANGELOG.md
Document-ru/CHANGELOG.md
Document/CHANGELOG.md

pre-release notes for english relese notes

---

Document-fr/CHANGELOG.md

French translation for changelog

---

Document-zhtw/Foreword.md

Translated Foreword to Traditional Chinese (zh-tw)

---

README.md

Bump to 1.1.4 :)

---

CONTRIBUTING.md

Fix numbered list which was not showing correctly

---

Document/0x11-V6-Interaction_with_the_environment.md

Add 6.9 requirement

---

Document-de/CHANGELOG.md

übersetzung ins deutsche

---

CONTRIBUTING.md

Following the chat on Slack, these are new instructions for setting up a translation.

First translation instructions

---

Document/0x07-V2-Data_Storage_and_Privacy_requirements.md

Small test for the page breaks on gitbook.

Test for gitbook tables

---

README.md

Updated to flagship status

---

Document/0x03-Using_the_MASVS.md
Document/CHANGELOG.md

This PR covers issue #277 & #189 .

277 masvs threatmodel

---

Document/0x07-V2-Data_Storage_and_Privacy_requirements.md
Document/0x09-V4-Authentication_and_Session_Management_Requirements.md

#276: moving requirements around

---

Document/0x07-V2-Data_Storage_and_Privacy_requirements.md

Rephrases the storage requirement based on #285

---

Document/0x06-V1-Architecture_design_and_threat_modelling_requireme.md

Fixed typo

---

Document/0x11-V6-Interaction_with_the_environment.md
Document/CHANGELOG.md

#304: added webview requirement as discussed

---

Document/0x03-Using_the_MASVS.md

#299: paid content explanation

---

CHANGELOG.md
Document/0x06-V1-Architecture_design_and_threat_modelling_requireme.md
Document/CHANGELOG.md

#297: added MSTG-ARCH-12 for following (privacy) laws

---

Document/0x07-V2-Data_Storage_and_Privacy_requirements.md
Document/0x08-V3-Cryptography_Verification_Requirements.md
Document/0x09-V4-Authentication_and_Session_Management_Requirements.md
Document/0x10-V5-Network_communication_requirements.md
Document/0x11-V6-Interaction_with_the_environment.md
Document/0x12-V7-Code_quality_and_build_setting_requirements.md
Document/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md

Consistency for #272

---

CHANGELOG.md
Document/0x11-V6-Interaction_with_the_environment.md
Document/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md

- [] In case of a translation: have you made sure that the translation from EN is as close to the EN document as possible?
This PR covers issue #313 & #133 .

313 133 new requirements

---

Document-de/0x03-Using_the_MASVS.md
Document-de/0x06-V1-Architecture_design_and_threat_modelling_requireme.md
Document-de/0x07-V2-Data_Storage_and_Privacy_requirements.md
Document-de/0x08-V3-Cryptography_Verification_Requirements.md
Document-de/0x09-V4-Authentication_and_Session_Management_Requirements.md
Document-de/0x10-V5-Network_communication_requirements.md
Document-de/0x11-V6-Interaction_with_the_environment.md
Document-de/0x12-V7-Code_quality_and_build_setting_requirements.md
Document-de/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md
Document-de/CHANGELOG.md

draft of German translation

---

Document-de/0x02-Frontispiece.md
README.md

Added korean translators to DE version

---

Document-ja/0x02-Frontispiece.md

added korean trnaslators and Randorisec into japanese translation

---

Document-ko/0x02-Frontispiece.md

Add Randorisec as Good Samaritan Benefactor

---

README.md

Updated slack invitation on README.md

---

README.md

add new language to the overview in readme

add new language to the overview in readme

---

.github/workflows/checkLinks.yml
.github/workflows/checkLint.yml
.github/workflows/docgenerator.yml
README.md

Automation 3

---

README.md
tools/docker/pandoc_makedocs.sh

#361: added epub and mobi metadata

---

Document-de/0x02-Frontispiece.md
Document-es/0x02-Frontispiece.md
Document-fr/0x02-Frontispiece.md
Document-ja/0x02-Frontispiece.md
Document-ko/0x02-Frontispiece.md
Document-ru/0x02-Frontispiece.md
Document-zhcn/0x02-Frontispiece.md
Document-zhtw/0x02-Frontispiece.md
Document/0x02-Frontispiece.md

Added chinese translation credits

---

.github/workflows/docgenerator.yml
.github/workflows/release.yml
.gitignore
tools/RECENT_CHANGES.TXT
tools/docker/pandoc_makedocs.sh
tools/docker/run_docker_masvs_generation_on_local.sh

#361:Added versioning (so not using SNAPSHOT for actual releases)

---

.github/workflows/release.yml

Automation 9

---

.github/workflows/release.yml

#361:Updated automated build for tags with some minor corrections

---

.github/workflows/release.yml

final corrections

---

tools/docker/latex-header.tex

Update of top margin:

---

.github/workflows/checkLint.yml
.github/workflows/docgenerator.yml

Add support for forks to be reviewed with new tooling

---

Document-fa/0x06-V1-Architecture_design_and_threat_modelling_requireme.md

* Update ‏0x06-V1-Architecture_design_and_threat_modelling_requireme.md
Co-authored-by: MahsaOmidvar <62174900+MahsaOmidvar@users.noreply.github.com>
This PR covers issue #399.

Translation of chapter 0x06 to Persian (#399)

---

.github/workflows/release.yml
tools/README.md

Change to release

---

Document-de/0x02-Frontispiece.md
Document-fr/0x02-Frontispiece.md
Document-ko/0x02-Frontispiece.md
tools/README.md

Slack urls updated

---

.github/workflows/checkLint.yml
.github/workflows/docgenerator.yml
tools/export.py

#415: Add hindi support in tooling (experimental)

---

Document-hi/template.yml
tools/Apply_Link_Check.sh
tools/Apply_Linter_Check.sh

Support for hindi improved

---

Document-ru/0x06-V1-Architecture_design_and_threat_modelling_requireme.md

Fix #427 small typo

---

Document-fa/0x06-V1-Architecture_design_and_threat_modelling_requireme.md
Document-hi/0x02-Frontispiece.md
Document-hi/0x06-V1-Architecture_design_and_threat_modelling_requireme.md
Document-hi/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md
Document-hi/0x91-Appendix-B_References.md

Updated urls again

---

.github/workflows/checkLint.yml

Apply lint check as it seems to drop out after merge mster backin

---

Document-hi/0x06-V1-Architecture_design_and_threat_modelling_requireme.md

Fixed a few broken urls

---

Document-fa/0x02-Frontispiece.md
Document-fa/0x06-V1-Architecture_design_and_threat_modelling_requireme.md

* Update 0x04-Assessment_and_Certification.md
Co-authored-by: Dorna Azhirak <@nameddorna>
Co-authored-by: Mahsa Omidvar <@MahsaOmidvar>
Co-authored-by: Alireza Mazhari <@alireza-mzhi>
This PR covers issue #401 .

Translation of chapter 0x04 to Persian (#401)

---

Document/0x02-Frontispiece.md

Update Persian Translators

---

Document/0x02-Frontispiece.md

Fix Persian Translators names

---

Document-zhcn/CHANGELOG.md

Update changelog.md for sim chinese

---

Document/0x02-Frontispiece.md

Version mismatch

---

.github/workflows/docgenerator.yml
.github/workflows/release.yml
README.md

Updated readme and release process so that all languages are in

---

README.md

fix document link in readme

---

Document-de/0x02-Frontispiece.md
Document-es/0x02-Frontispiece.md
Document-fr/0x02-Frontispiece.md
Document-ja/0x02-Frontispiece.md
Document-ko/0x02-Frontispiece.md
Document-ptbr/0x02-Frontispiece.md
Document-ru/0x02-Frontispiece.md
Document-zhcn/0x02-Frontispiece.md
Document-zhtw/0x02-Frontispiece.md
Document/0x02-Frontispiece.md

Added Hindi Translators

---

Document-ru/0x12-V7-Code_quality_and_build_setting_requirements.md

#460: fixed link for referencing to iOS

---

Document-ptpt/0x02-Frontispiece.md

This PR is a WIP for issue #467

Translation PTPT 0x02-Frontispiece

---

.github/workflows/checkLint.yml
.github/workflows/docgenerator.yml
.github/workflows/release.yml
Document-ptpt/0x02-Frontispiece.md
Document-ptpt/LANGUAGE-METADATA

Updated Portuguese automation

---

Document-ptpt/0x06-V1-Architecture_design_and_threat_modelling_requireme.md
Document-ptpt/0x10-V5-Network_communication_requirements.md
Document-ptpt/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md

This PR is a WIP for issue #467

Some translations for PT-PT

---

Document-ptpt/LANGUAGE-METADATA

This PR is a WIP for issue #467.

adding some ptpt specific metadata

---

Document-ptpt/0x02-Frontispiece.md

Fix typos.

---

CODE_OF_CONDUCT.md

removed myself from the project team mail list

---

Document-ptpt/0x02-Frontispiece.md
Document-ptpt/0x03-Using_the_MASVS.md

Document ptpt 0x03

---

Document-ptpt/0x04-Assessment_and_Certification.md
Document-ptpt/0x07-V2-Data_Storage_and_Privacy_requirements.md
Document-ptpt/0x09-V4-Authentication_and_Session_Management_Requirements.md
Document-ptpt/0x11-V6-Interaction_with_the_environment.md
Document-ptpt/0x12-V7-Code_quality_and_build_setting_requirements.md
Document-ptpt/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md
Document-ptpt/SUMMARY.md
README.md

FInal checks for PT-PT Translation

---

.github/workflows/docgenerator.yml

Use a separate conditional job to retrieve all artifacts and put them to the release.

retrieve all artifacts for release

---

.github/workflows/docgenerator.yml

fix how to read files for release

---

Document-ptbr/0x15-V8-Resiliency_Against_Reverse_Engineering_Requirements.md

Verbal Agreement

---

README.md

added support for non-latin fonts

---

README.md

changed filename for local build

---

.github/workflows/checkLinks.yml
.github/workflows/checkLint.yml
Document-ptbr/GLOSSARY.md
Document-ru/SUMMARY.md

Upgrade URL Checker and Linter & Fix Broken Link

---

.github/workflows/docgenerator.yml

Try to avoid having to edit the workflow file for each release by reading GITHUB_REF

try using GITHUB_REF

---

.github/workflows/doc-gen-reusable.yml
.github/workflows/docgenerator.yml

The latest tag wasn't properly retrieved, now we get it via curl.

Fix no tag issue

---

README.md

It's a bit of inconvenience to have broken link in main README.md :)

update README.md link to match latest pdf release

---

.gitignore
.vscode/extensions.json
.vscode/settings.json

Add default colors and extensions.

add vscode settings

---

README.md

Add the Trusted by section linking back to the MSTG.

Add Tusted By section

---

README.md

Fix Read MASVS Link

---

Document/0x03-Using_the_MASVS.md

Add SDK and preload applicability

---

tools/generate_masvs_cyclonedx.py
tools/populate_masvs_categories_md.py

This is a minor update to #715 that updates the script so that the output is compliant with the current draft of CycloneDX v1.6. No further changes are expected.
---
> Note: Thank you for submitting a Pull Request to the OWASP MASVS repo! By opening a PR you're agreeing with our [contribution guidelines](https://github.com/OWASP/owasp-masvs/blob/master/CONTRIBUTING.md "Contribution guidelines").

Update to CycloneDX v1.6 standards support

---

tools/populate_masvs_categories_md.py

This script is also used by the MASTG for the website and needs some fixes.

fix script
